'use server'

import { createClient } from '@supabase/supabase-js'
import { createServiceClient } from '@/lib/supabase/service'
/* Code generated by AI, to delete an account in Supabase */
/**
 * Server Action to completely delete a company and all associated data
 * This runs on the server with admin privileges to bypass RLS
 */
export async function deleteCompanyAndUser(companyId: string) {
    // Create admin client with service role key (bypasses RLS)
    const supabaseAdmin = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.SUPABASE_SECRET_KEY!,
        {
            auth: {
                autoRefreshToken: false,
                persistSession: false
            }
        }
    )

    console.log('🗑️ Starting server-side deletion for company:', companyId)

    // 1. Check for active offers
    const { data: offers, error: offersError } = await supabaseAdmin
        .from('offers')
        .select('id, status')
        .eq('company_id', companyId)

    if (offersError) {
        throw new Error('Impossible de vérifier les offres')
    }

    if (offers && offers.length > 0) {
        const activeOffers = offers.filter(offer => offer.status === 'available')

        if (activeOffers.length > 0) {
            throw new Error(`Impossible de supprimer l'entreprise. Vous avez ${activeOffers.length} offre(s) active(s). Veuillez d'abord les expirer ou les marquer comme pourvues.`)
        }

        // 2. Check for applications on offers
        const offerIds = offers.map(offer => offer.id)
        const { data: applications, error: appsError } = await supabaseAdmin
            .from('applications')
            .select('id')
            .in('offer_id', offerIds)

        if (appsError) {
            throw new Error('Impossible de vérifier les candidatures')
        }

        if (applications && applications.length > 0) {
            throw new Error(`Impossible de supprimer l'entreprise. Il existe ${applications.length} candidature(s) associée(s) à vos offres.`)
        }

        // 3. Delete offers (all expired/filled with no applications)
        const { error: deleteOffersError } = await supabaseAdmin
            .from('offers')
            .delete()
            .eq('company_id', companyId)

        if (deleteOffersError) {
            throw new Error('Erreur lors de la suppression des offres')
        }
        console.log('✅ Offers deleted')
    }

    // 4. Get company owner_id
    const { data: company, error: fetchError } = await supabaseAdmin
        .from('companies')
        .select('owner_id')
        .eq('id', companyId)
        .single()

    if (fetchError || !company) {
        throw new Error('Entreprise introuvable')
    }

    const ownerId = company.owner_id

    // 5. Delete the company
    const { error: companyError } = await supabaseAdmin
        .from('companies')
        .delete()
        .eq('id', companyId)

    if (companyError) {
        throw new Error('Erreur lors de la suppression de l\'entreprise')
    }
    console.log('✅ Company deleted')

    // 6. Delete the profile
    const { error: profileError } = await supabaseAdmin
        .from('profiles')
        .delete()
        .eq('id', ownerId)

    if (profileError) {
        throw new Error('Erreur lors de la suppression du profil')
    }
    console.log('✅ Profile deleted')

    // 7. Try to delete auth user
    const { error: authError } = await supabaseAdmin.auth.admin.deleteUser(ownerId)

    if (authError) {
        console.error('⚠️ Could not delete auth user:', authError.message)
    } else {
        console.log('✅ Auth user deleted')
    }
}

export async function deleteStudentAndUser(userId: string) {
    const supabaseAdmin = createServiceClient()

    console.log('🗑️ Starting deletion for student:', userId)

    // 1. Fetch cv_path from students
    const { data: student } = await supabaseAdmin
        .from('students')
        .select('cv_path')
        .eq('user_id', userId)
        .single()

    // 2. Delete CV from storage if it exists
    if (student?.cv_path) {
        const { error: storageError } = await supabaseAdmin.storage
            .from('cvs')
            .remove([student.cv_path])
        if (storageError) {
            console.error('⚠️ Could not delete CV file, continuing:', storageError.message)
        } else {
            console.log('✅ CV file deleted')
        }
    }

    // 3. Delete student_skills
    const { error: skillsError } = await supabaseAdmin
        .from('student_skills')
        .delete()
        .eq('student_id', userId)
    if (skillsError) throw new Error('Erreur lors de la suppression des compétences')
    console.log('✅ Student skills deleted')

    // 4. Fetch application IDs for this student
    const { data: applications, error: appsSelectError } = await supabaseAdmin
        .from('applications')
        .select('id')
        .eq('student_id', userId)
    if (appsSelectError) throw new Error('Erreur lors de la récupération des candidatures')

    // 5. Delete reviews for those applications
    if (applications && applications.length > 0) {
        const appIds = applications.map(a => a.id)
        const { error: reviewsError } = await supabaseAdmin
            .from('reviews')
            .delete()
            .in('application_id', appIds)
        if (reviewsError) throw new Error('Erreur lors de la suppression des évaluations')
        console.log('✅ Reviews deleted')
    }

    // 6. Delete applications
    const { error: appsError } = await supabaseAdmin
        .from('applications')
        .delete()
        .eq('student_id', userId)
    if (appsError) throw new Error('Erreur lors de la suppression des candidatures')
    console.log('✅ Applications deleted')

    // 7. Delete students row
    const { error: studentError } = await supabaseAdmin
        .from('students')
        .delete()
        .eq('user_id', userId)
    if (studentError) throw new Error('Erreur lors de la suppression du profil étudiant')
    console.log('✅ Student record deleted')

    // 8. Delete profile
    const { error: profileError } = await supabaseAdmin
        .from('profiles')
        .delete()
        .eq('id', userId)
    if (profileError) throw new Error('Erreur lors de la suppression du profil')
    console.log('✅ Profile deleted')

    // 9. Delete auth user
    const { error: authError } = await supabaseAdmin.auth.admin.deleteUser(userId)
    if (authError) {
        console.error('⚠️ Could not delete auth user:', authError.message)
    } else {
        console.log('✅ Auth user deleted')
    }
}

